spring:
  kafka:
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    producer:
      properties:
        spring:
          json:
            trusted:
              packages: "*"
spring.cloud.stream:
  function:
    definition: kStreamConsumer
  bindings:
    kStreamConsumer-in-0:
      destination: test
  kafka:
    bindings:
      kStreamConsumer-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    binder:
      consumer-properties:
        spring.json.trusted.packages: com.ck.dev.kafkaconsumercloudstream.domain

      brokers:
        - localhost:9092