version: "2.1"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-poc
    ports:
      - "3181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    mem_limit: 256m

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-poc
    depends_on:
      - zookeeper
    ports:
      - "10092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:10092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    mem_limit: 768m

  kafka_admin:
    image: obsidiandynamics/kafdrop
    container_name: kafka-admin-poc
    depends_on:
      - kafka
    ports:
      - "10000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
    mem_limit: 256m
